### ISSUE TITLE
Report results fails when running in Github Enterprise

### ISSUE THREAD

**Issue by xhujerr** [getunlatch/jscpd-github-action#4]
Hello,
I'm trying to run your actions in GHE `github.mycompany.com`.

The action fails with an error:
```
Run actions/jscpd-github-action@v1.2
  with:
    repo-token: ***
HTML report saved to report/html/
Markdown report saved to report/jscpd-report.md
/var/actions-runner/share/runner/_work/_actions/actions/jscpd-github-action/v1.2/node_modules/octokit/node_modules/@octokit/request/dist-node/index.js:88
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
    at /var/actions-runner/share/runner/_work/_actions/actions/jscpd-github-action/v1.2/node_modules/octokit/node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/var/actions-runner/share/runner/_work/_actions/actions/jscpd-github-action/v1.2/node_modules/bottleneck/light.js:405:18) {
  status: 401,
  response: {
    url: 'https://api.github.com/repos/cia/rpl-tools/pulls/264',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 03 Jul 2023 12:56:35 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; param=diff',
      'x-github-request-id': '4C99:01DD:8EAF359:9347154:64A2C583',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '58',
      'x-ratelimit-reset': '1688392272',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '2',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/cia/rpl-tools/pulls/264',
    headers: {
      accept: 'application/vnd.github.v3.diff',
      'user-agent': 'octokit.js/2.0.10 octokit-core.js/4.1.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

It appears to me that it tries to post the report to `github.com` instead of `github.mycompany.com`. Where can I set up the correct endpoint for a report upload?

**Comment by oadam** [comment]
I am clueless as there is no mention of github.com in the code : https://github.com/getunlatch/jscpd-github-action/blob/main/main.js
If you find a lead, don't hesitate to open a PR :pray:

**Comment by xhujerr** [comment]
It started to work since the last July.
Cannot really say what was the problem or when it started to work. 
Feel free to close the issue.
